---
- hosts: localhost
  gather_facts: no
  module_defaults:
    group/aws:
      region: "us-west-1"
  tasks:
    - name: create asg
      ec2_asg:
        name: m5-asg
        load_balancers: m5demo-target-group.load_balancer_arns
        availability_zones: [ 'us-west-1a', 'us-west-1c' ]
        launch_template: 
          launch_template_name: m5demo-nginxserver-lt
          version: "latest"
        min_size: 1
        max_size: 4
        desired_capacity: 1
        vpc_zone_identifier: 
          - subnet_public_demo
          - subnet_public_demo2
