---
- hosts: localhost
  gather_facts: no
  module_defaults:
    group/aws:
      region: "us-west-1"
  tasks:
    - name: Create network load balancer
      elb_network_lb:
        name: m5demo-nlb
        subnet_mappings:
          - SubnetId: "{{ subnet_public_demo.subnet.id }}"
            AllocationId: eipalloc-090a7233941caebf5
          - SubnetId: "{{ subnet_public_demo2.subnet.id }}"
            AllocationId: eipalloc-0011f238e9e63f3bb
        listeners:
          - Protocol: TCP 
            Port: 80
            DefaultActions:
              - Type: forward 
                TargetGroupName: m5demo-target-group
          - Protocol: TLS
            Port: 443
            DefaultActions:
              - Type: forward 
                TargetGroupName: m5demo-target-group
            Certificates:
              - CertificateArn: arn:aws:acm:us-west-1:719573831279:certificate/9ae8db90-f6be-48cd-a599-8c2dfb1833e4
        state: present
    - name: Update route 53 entry w new nlb az eips replicated
      route53:
        region: "us-west-1"
        zone: ariana-g.com
        record: ariana-g.com
        identifier: ariana-g.com
        overwrite: yes
        type: A
        ttl: 7200
        value:
          - 184.72.1.65
          - 52.9.246.95
        wait: yes
        state: present
    - name: Update www route 53 entry w new nlb az eips replicated
      route53:
        region: "us-west-1"
        zone: ariana-g.com
        record: www.ariana-g.com
        identifier: ariana-g.com
        overwrite: yes
        type: A
        ttl: 7200
        value:
          - 184.72.1.65
          - 52.9.246.95
        wait: yes
        state: present
