---
- hosts: localhost
  gather_facts: no
  module_defaults:
    group/aws:
      region: "us-west-1"
  tasks:
    - name: Create autoscale group launch template
      ec2_launch_template:
        name: m5demo-nginxserver-lt
        image_id: "ami-04e59c05167ea7bd5"
        key_name: module1keypair
        instance_type: t2.micro
#        iam_instance_profile: m5demorole(so has aws cli to s3 and secrets)
        network_interfaces:
          -  associate_public_ip_address: yes
        user_data: "{{ lookup('file', 'ec2-prod-bootstrap64.txt') }}"
        tags:
          Name: m5-nginx-server-asg
        security_groups: 
          - m5demo-nginx-server-asg
          - m5demo-postgrestag-sg