---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: Create VPC
      ec2_vpc_net:
        name: Module5Demo
        cidr_block: 10.5.0.0/16
        tags:
          Module: 5
#       region: "us-west-1"
        state: present