---
- hosts: localhost
  gather_facts: no
  module_defaults:
    group/aws:
      region: "us-west-1"
  tasks:
#    - name: debug nlb
#      debug: var=m5demo-nlb
    - name: create asg
      ec2_asg:
        name: m5-asg
        load_balancers: m5demo-nlb.load_balancer_arn
#        target_group_arns: m5demo-target-group.arn
        min_size: 1
        max_size: 4
        desired_capacity: 1
        vpc_zone_identifier: 
          - '{{ subnet_public_demo.subnet.id }}'
          - '{{ subnet_public_demo2.subnet.id }}'
        launch_template: 
          launch_template_name: m5-nginxserver-lt
          version: '$Latest'