---
- hosts: localhost
  gather_facts: no
  module_defaults:
    group/aws:
      region: "us-west-1"
  tasks:
    - name: Create target group
      elb_target_group:
        name: m5demo-target-group
        stickiness_enabled: no
        stickiness_type: source_ip
        target_type: instance
        protocol: TCP
        port: 80
        vpc_id: "{{ vpc_demo.vpc.id }}"
        state: present
  
