---
- hosts: localhost
  gather_facts: no
  module_defaults:
    group/aws:
      region: "us-west-1"
  tasks:
    - name: Create target group
      elb_target_group:
        name: m5demo-target-group
        stickiness_enabled: no
        stickiness_type: source_ip
        target_type: instance
        protocol: TCP
        port: 80
        vpc_id: "{{ vpc_demo.vpc.id }}"
        state: present
    - name: Create network load balancer
      elb_network_lb:
        name: m5demo-nlb
        subnets:
          - "{{ subnet_public_demo.subnet.id }}"
          - "{{ subnet_public_demo2.subnet.id }}"
        listeners:
          - Protocol: TCP 
            Port: 80
            DefaultActions:
              - Type: forward 
                TargetGroupName: m5demo-target-group
          - Protocol: TLS
            Port: 443
            DefaultActions:
              - Type: forward 
                TargetGroupName: m5demo-target-group
            Certificates:
              - CertificateArn: arn:aws:acm:us-west-1:719573831279:certificate/9ae8db90-f6be-48cd-a599-8c2dfb1833e4
        state: present 
