---
- hosts: localhost
  gather_facts: no
  module_defaults:
    group/aws:
      region: "us-west-1"
  tasks:
    - name: Create VPC
      ec2_vpc_net:
        name: Module5Demo
        cidr_block: 10.5.0.0/16
        tags:
          Module: 5
        state: present
      register: vpc_demo
    - name: debug
      debug: var=vpc_demo
    - name: Create public subnet 1
      ec2_vpc_subnet:
        vpc_id: "{{ vpc_demo.vpc.id }}"
        tags:
          Name: Module5 public demo
          Module: 5
        az: "us-west-1a"
        cidr: 10.5.0.0/24
        state: present
        map_public: yes
      register: subnet_public_demo
    - name: Create public subnet 2
      ec2_vpc_subnet:
        vpc_id: "{{ vpc_demo.vpc.id }}"
        tags:
          Name: Module5 public demo
          Module: 5
        az: "us-west-1c"
        cidr: 10.5.2.0/24
        state: present
        map_public: yes
      register: subnet_public_demo2
    - name: Create private subnet
      ec2_vpc_subnet:
        vpc_id: "{{ vpc_demo.vpc.id }}"
        tags:
          Name: Module5 private demo
          Module: 5
        az: "us-west-1a"
        cidr: 10.5.1.0/24
        state: present
      register: subnet_private_demo
    - name: Create private subnet
      ec2_vpc_subnet:
        vpc_id: "{{ vpc_demo.vpc.id }}"
        tags:
          Name: Module5 private demo
          Module: 5
        az: "us-west-1c"
        cidr: 10.5.3.0/24
        state: present
      register: subnet_private_demo2 
    - name: Create igw
      ec2_vpc_igw:
        vpc_id: "{{ vpc_demo.vpc.id }}"
        tags:
          Name: Module 5 demo gateway
        state: present
      register: igw_demo
    - name: Create new nat gateway and allocate new EIP if a nat gateway does not yet exist in the subnet.
      ec2_vpc_nat_gateway:
        subnet_id: "{{ subnet_public_demo.subnet.id }}"
        state: present
        wait: yes
        if_exist_do_not_create: true
      register: m5demo_ng
    - name: Create public route table
      ec2_vpc_route_table:
        vpc_id: "{{ vpc_demo.vpc.id }}"
        tags:
          Name: Module5demoRTBL
        subnets:
          - "{{ subnet_public_demo.subnet.id }}"
          - "{{ subnet_public_demo2.subnet.id }}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ igw_demo.gateway_id }}"
        state: present
    - name: Create private route table
      ec2_vpc_route_table:
        vpc_id: "{{ vpc_demo.vpc.id }}"
        tags:
          Name: Module5demoRTBLprivate
        subnets:
          - "{{ subnet_private_demo.subnet.id }}"
          - "{{ subnet_private_demo2.subnet.id }}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ m5demo_ng.nat_gateway_id }}"
        state: present
