---
- hosts: localhost
  gather_facts: no
  module_defaults:
    group/aws:
      region: "us-west-1"
  tasks:
    - name: Create nginx servers autoscaling group sg
      ec2_group:
        name: m5demo-nginx-server-asg
        description: nginx load balanced servers
        vpc_id: "{{ vpc_demo.vpc.id }}"
        rules:
          - proto: tcp
            ports:
            - 80
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            ports:
            - 443
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            ports:
            - 22
            cidr_ip: 0.0.0.0/0
    - name: Create m5 demo devel security group
      ec2_group:
        name: Module5-devel-demo-sg
        description: m5 demo devel sec group
        vpc_id: "{{ vpc_demo.vpc.id }}"
        state: present
        rules:
          - proto: tcp
            ports:
              - 5000
              - 5555
            cidr_ip:
              - 70.95.135.156/32
              - 24.196.25.139/32
              - 24.239.105.213/32
          - proto: tcp
            ports: 22
            cidr_ip: 0.0.0.0/0
    - name: Create NLB sg
      ec2_group:
        name: Module5-NLB-demo-sg
        description: m5 demo nlb sec group
        vpc_id: "{{ vpc_demo.vpc.id }}"
        state: present
        rules:
          - proto: tcp
            ports:
              - 80
              - 443
            cidr_ip:
              - 70.95.135.156/32
              - 24.196.25.139/32
              - 24.239.105.213/32 
    - name: Create postgres sg
      ec2_group:
        name: m5demo-postgres-asg
        description: m5 demo postgres sg
        vpc_id: "{{ vpc_demo.vpc.id }}"
        rules:
          - proto: tcp
            ports:
            - 5432
            cidr_ip: "{{ m5demo_postgrestag_sg.group_id }}"
        register: m5demo_postgres_sg   
    - name: Create postgres-tag sg
      ec2_group:
        name: m5demo-postgrestag-asg
        description: m5 demo postgres tag sg
        vpc_id: "{{ vpc_demo.vpc.id }}"
        rules_egress:
          - proto: tcp
            ports:
            - 5432
            cidr_ip: "{{ m5demo_postgres_sg.group_id }}"    
      register: m5demo_potgrestag_sg
