---
- hosts: localhost
  gather_facts: no
  module_defaults:
    group/aws:
      region: "us-west-1"
  tasks:
    - name: Create m5 asg server role
      iam_role:
        name: m5server-role
        assume_role_policy_document: "{{ lookup('file','assume_role_policy.json') }}"
        managed_policy:
          - arn:aws:iam::719573831279:policy/image_gallery_s3_policy
          -  arn:aws:iam::719573831279:policy/image_gallery_secrets_policy
        description: M5 server accesses s3 and secrets