---
- hosts: localhost
  gather_facts: no
  module_defaults:
    group/aws:
      region: "us-west-1"
  tasks:
    -name: Create target group
     elb_target_group:
       name: m5demo-target-group
       target_type: instance
       protocol: tcp
       port: 80
       vpc_id: "{{ vpc_demo.vpc.id }}"
       state: present
    -name: Create network load balancer
     elb_network_lb:
       name: m5demo-nlb
       subnets_mappings:
         - "{{ subnet_demo_public }}"
         - "{{ subnet_demo_public2 }}"
       listeners:
         - Protocol: TCP 
           Port: 80 
         - Protocol: TLS
           Port: 443
        DefaultActions:
          - Type: forward 
            TargetGroupName: m5demo-target-group 
       state: present 